### ISSUE TITLE
Website not loading.

### ISSUE THREAD

**Issue by Joseffb** [wp-graphql/docs.wpgraphql.com#47] opened 2019-04-08 12:57 UTC
getting a redirect issue on docs.wpgraphql.com

**Comment by Joseffb** [comment] 2019-04-08 13:04
seems to only happen on my secure browser so it's probably cookie issue. 

The page isn’t redirecting properly

An error occurred during a connection to docs.wpgraphql.com.

    This problem can sometimes be caused by disabling or refusing to accept cookies.

**Comment by jasonbahl** [comment] 2019-04-08 20:29
@Joseffb are you still having this issue? Site seems ok on a few different browsers and devices for me.

**Comment by Joseffb** [comment] 2019-04-08 20:32
Yea it’s a cookie issue. I haven't had time to investigate/ fix it other then what I posted. 

Experienced on Firefox defaulted to private mode with a whole assortment of ad blockers and anti-anti-ad blockers. 

My work machine (no blockers in regular mode) is fine.

**Comment by jasonbahl** [comment] 2019-04-08 20:37
Oh weird. I don’t serve up any ads at all on the site. . .so I have no clue what would be happening. 

I do send page views to Google Analytics, so possibly that’s it?

Not sure I care to prioritize fixing to cater to adblockers though. Would cause a support burden I’m not particularly interested in chasing. ¯\_(ツ)_/¯

Happy to address if you have thoughts though. 

Thanks,

Jason

**Comment by Joseffb** [comment] 2019-04-08 20:40
The GA makes sense, but to be honest such a small use case I wouldn't worry.

If you have a browser build like mine (I hate ads!) then your technical enough to disable it if you don’t already have a clean alt browser for this type of stuff.

**Comment by Joseffb** [comment] 2019-04-09 13:42
Ok weird. Today in office on my clean browsers (firefox, safari, and google) I got the error agains. Then five minutes later they resolved fine and business as usual. 

Maybe check out the dns settings to make sure its not something worse.

**Comment by jasonbahl** [comment] 2019-04-09 16:14
Hmm. Ya, maybe it is a weird DNS issue. 🤔

**Comment by esamattis** [comment] 2019-05-03 07:41
I've seen this happen few times. Not able to reproduce it currently though.

**Comment by hypnoboutique** [comment] 2019-06-26 10:45
`https://docs.wpgraphql.com/9-7e2f23e5b8b5af7f363d.js net::ERR_TOO_MANY_REDIRECTS`
 when visiting https://docs.wpgraphql.com/ (root)

I **can** reach docs if I visit a named route, eg [Details on Install and Activation](https://docs.wpgraphql.com/getting-started/install-and-activate/) from the README.md

**Comment by jasonbahl** [comment] 2019-07-29 17:32
I made some DNS changes a few weeks ago and I believe the site has been stable since. 

Closing this issue, but if it comes up again we can re-visit.

**Closed as completed by jasonbahl** 2019-07-29 17:32 UTC
